# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/analyzer/v1/analyzer.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional

import betterproto
import grpclib


@dataclass
class ParseRequest(betterproto.Message):
    """структура для передачи данных в анализатор"""

    text: str = betterproto.string_field(1)
    user_id: str = betterproto.string_field(2)
    locale: str = betterproto.string_field(3)
    timezone: str = betterproto.string_field(4)
    timestamp: datetime = betterproto.message_field(5)


@dataclass
class ParseResponse(betterproto.Message):
    """
    структура для получения ответа от анализатора для оповещения пользователя
    """

    status: str = betterproto.string_field(1)


@dataclass
class Event(betterproto.Message):
    name: str = betterproto.string_field(1)
    start_time: datetime = betterproto.message_field(2)
    finish_time: datetime = betterproto.message_field(3)
    participants: List[str] = betterproto.string_field(4)


class AnalyzerServiceStub(betterproto.ServiceStub):
    """метод для взаимодействия"""

    async def parse(
        self,
        *,
        text: str = "",
        user_id: str = "",
        locale: str = "",
        timezone: str = "",
        timestamp: Optional[datetime] = None,
    ) -> ParseResponse:
        request = ParseRequest()
        request.text = text
        request.user_id = user_id
        request.locale = locale
        request.timezone = timezone
        if timestamp is not None:
            request.timestamp = timestamp

        return await self._unary_unary(
            "/analyzer.v1.AnalyzerService/Parse",
            request,
            ParseResponse,
        )
