env: "local"
database_url: "postgresql://postgres.fjpgtkbfdzhcalraskan:USX36hFfw1jPfe4P@aws-1-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require"
storage_timeout: "5s"
token_ttl: "1h"

grpc:
  port: 50051
  timeout: "5s"

google:
  client_id: ""
  client_secret: ""

