env: "local"
database_url: "postgres://postgres:postgres@localhost:5432/calendar_db?sslmode=disable"
storage_timeout: "5s"
token_ttl: "1h"

grpc:
  port: 50051
  timeout: "5s"

google:
  client_id: "your-google-client-id"
  client_secret: "your-google-client-secret"
