# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: proto/analyzer/v1/analyzer.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = ("AnalyzerServiceStub", "ParseRequest", "ParseResponse", "SendEvent")

import datetime
from dataclasses import dataclass

import betterproto2
import grpc

from ...message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class ParseRequest(betterproto2.Message):
    """
    структура для передачи данных в анализатор
    """

    text: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    текстовое сообщение пользователя в боте
    """

    user_id: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)
    """
    id пользователя
    """

    locale: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)
    """
    язык текста
    """

    timezone: "str" = betterproto2.field(4, betterproto2.TYPE_STRING)
    """
    часовой пояс
    """

    timestamp: "datetime.datetime | None" = betterproto2.field(
        5,
        betterproto2.TYPE_MESSAGE,
        unwrap=lambda: __google__protobuf__.Timestamp,
        optional=True,
    )
    """
    время отправки сообщения
    """


default_message_pool.register_message("analyzer.v1", "ParseRequest", ParseRequest)


@dataclass(eq=False, repr=False)
class ParseResponse(betterproto2.Message):
    """
    структура для получения ответа от анализатора для оповещения пользователя
    """

    status: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)
    """
    "accepted" | "error"
    """


default_message_pool.register_message("analyzer.v1", "ParseResponse", ParseResponse)


@dataclass(eq=False, repr=False)
class SendEvent(betterproto2.Message):
    name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    start_time: "datetime.datetime | None" = betterproto2.field(
        2,
        betterproto2.TYPE_MESSAGE,
        unwrap=lambda: __google__protobuf__.Timestamp,
        optional=True,
    )

    finish_time: "datetime.datetime | None" = betterproto2.field(
        3,
        betterproto2.TYPE_MESSAGE,
        unwrap=lambda: __google__protobuf__.Timestamp,
        optional=True,
    )

    participants: "list[str]" = betterproto2.field(
        4, betterproto2.TYPE_STRING, repeated=True
    )


default_message_pool.register_message("analyzer.v1", "SendEvent", SendEvent)


class AnalyzerServiceStub:
    """
    метод для взаимодействия
    """

    def __init__(self, channel: grpc.Channel):
        self._channel = channel

    def parse(self, message: "ParseRequest") -> "ParseResponse":
        return self._channel.unary_unary(
            "/analyzer.v1.AnalyzerService/Parse",
            ParseRequest.SerializeToString,
            ParseResponse.FromString,
        )(message)


from ...google import protobuf as __google__protobuf__
