# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: analyzer/v1/analyzer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61nalyzer/v1/analyzer.proto\x12\x0b\x61nalyzer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Y\n\x12\x41nalyzeTextRequest\x12\x12\n\ntg_user_id\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08timezone\x18\x03 \x01(\t\x12\x0f\n\x07\x63hat_id\x18\x04 \x01(\x03\"\xb4\x01\n\x13\x41nalyzeTextResponse\x12\x30\n\x0c\x63reate_event\x18\x01 \x01(\x0b\x32\x18.analyzer.v1.CreateEventH\x00\x12<\n\x12need_clarification\x18\x02 \x01(\x0b\x32\x1e.analyzer.v1.NeedClarificationH\x00\x12#\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x12.analyzer.v1.ErrorH\x00\x42\x08\n\x06result\"\x8f\x01\n\x0b\x43reateEvent\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12.\n\nstart_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"%\n\x11NeedClarification\x12\x10\n\x08question\x18\x01 \x01(\t\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t2c\n\x0f\x41nalyzerService\x12P\n\x0b\x41nalyzeText\x12\x1f.analyzer.v1.AnalyzeTextRequest\x1a .analyzer.v1.AnalyzeTextResponseBLZJgithub.com/andrepribavkin/calendar-management/proto/analyzer/v1;analyzerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyzer.v1.analyzer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/andrepribavkin/calendar-management/proto/analyzer/v1;analyzerv1'
  _globals['_ANALYZETEXTREQUEST']._serialized_start=76
  _globals['_ANALYZETEXTREQUEST']._serialized_end=165
  _globals['_ANALYZETEXTRESPONSE']._serialized_start=168
  _globals['_ANALYZETEXTRESPONSE']._serialized_end=348
  _globals['_CREATEEVENT']._serialized_start=351
  _globals['_CREATEEVENT']._serialized_end=494
  _globals['_NEEDCLARIFICATION']._serialized_start=496
  _globals['_NEEDCLARIFICATION']._serialized_end=533
  _globals['_ERROR']._serialized_start=535
  _globals['_ERROR']._serialized_end=559
  _globals['_ANALYZERSERVICE']._serialized_start=561
  _globals['_ANALYZERSERVICE']._serialized_end=660
# @@protoc_insertion_point(module_scope)
