# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import router_pb2 as router_dot_proto_dot_router_dot_router__pb2


class SchedulerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEvent = channel.unary_unary(
                '/scheduler.Scheduler/CreateEvent',
                request_serializer=router_dot_proto_dot_router_dot_router__pb2.CreateEventRequest.SerializeToString,
                response_deserializer=router_dot_proto_dot_router_dot_router__pb2.CreateEventResponse.FromString,
                )
        self.CreateTask = channel.unary_unary(
                '/scheduler.Scheduler/CreateTask',
                request_serializer=router_dot_proto_dot_router_dot_router__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=router_dot_proto_dot_router_dot_router__pb2.CreateTaskResponse.FromString,
                )


class SchedulerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEvent,
                    request_deserializer=router_dot_proto_dot_router_dot_router__pb2.CreateEventRequest.FromString,
                    response_serializer=router_dot_proto_dot_router_dot_router__pb2.CreateEventResponse.SerializeToString,
            ),
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=router_dot_proto_dot_router_dot_router__pb2.CreateTaskRequest.FromString,
                    response_serializer=router_dot_proto_dot_router_dot_router__pb2.CreateTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduler.Scheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Scheduler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scheduler.Scheduler/CreateEvent',
            router_dot_proto_dot_router_dot_router__pb2.CreateEventRequest.SerializeToString,
            router_dot_proto_dot_router_dot_router__pb2.CreateEventResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scheduler.Scheduler/CreateTask',
            router_dot_proto_dot_router_dot_router__pb2.CreateTaskRequest.SerializeToString,
            router_dot_proto_dot_router_dot_router__pb2.CreateTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
