# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: router/proto/router/router.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n router/proto/router/router.proto\x12\tscheduler\x1a\x1fgoogle/protobuf/timestamp.proto\"i\n\tDateRange\x12.\n\nstart_date\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"u\n\rDateTimeRange\x12\x32\n\x0estart_datetime\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0c\x65nd_datetime\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xbb\x01\n\x12\x43reateEventRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x14\n\x0cparticipants\x18\x03 \x03(\t\x12$\n\x04\x64\x61te\x18\x04 \x01(\x0b\x32\x14.scheduler.DateRangeH\x00\x12,\n\x08\x64\x61tetime\x18\x05 \x01(\x0b\x32\x18.scheduler.DateTimeRangeH\x00\x12\x0f\n\x07user_id\x18\x06 \x01(\tB\x06\n\x04time\"2\n\x13\x43reateEventResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t\"H\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"1\n\x12\x43reateTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t2\xa4\x01\n\tScheduler\x12L\n\x0b\x43reateEvent\x12\x1d.scheduler.CreateEventRequest\x1a\x1e.scheduler.CreateEventResponse\x12I\n\nCreateTask\x12\x1c.scheduler.CreateTaskRequest\x1a\x1d.scheduler.CreateTaskResponseB)Z\'calendar_management/routerv0; routerv0 b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'router.proto.router.router_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'calendar_management/routerv0; routerv0 '
  _globals['_DATERANGE']._serialized_start=80
  _globals['_DATERANGE']._serialized_end=185
  _globals['_DATETIMERANGE']._serialized_start=187
  _globals['_DATETIMERANGE']._serialized_end=304
  _globals['_CREATEEVENTREQUEST']._serialized_start=307
  _globals['_CREATEEVENTREQUEST']._serialized_end=494
  _globals['_CREATEEVENTRESPONSE']._serialized_start=496
  _globals['_CREATEEVENTRESPONSE']._serialized_end=546
  _globals['_CREATETASKREQUEST']._serialized_start=548
  _globals['_CREATETASKREQUEST']._serialized_end=620
  _globals['_CREATETASKRESPONSE']._serialized_start=622
  _globals['_CREATETASKRESPONSE']._serialized_end=671
  _globals['_SCHEDULER']._serialized_start=674
  _globals['_SCHEDULER']._serialized_end=838
# @@protoc_insertion_point(module_scope)
